USE ROLE ACCOUNTADMIN; -- SECURITYADMIN / ACCOUNTADMIN

CREATE ROLE IF NOT EXISTS ANALYST_ROLE COMMENT = 'Role for data analysts.';
GRANT ROLE CLASS_ANALYST_ROLE TO ROLE SYSADMIN;





CREATE ROLE IF NOT EXISTS MONTE_CARLO_ROLE COMMENT = 'Role for Monte Carlo data monitoring.';


-- 4. Grant the role and warehouse usage
-- GRANT ROLE MONTE_CARLO_ROLE TO USER MONTE_CARLO_USER;
-- GRANT USAGE ON WAREHOUSE MONTE_CARLO_WH TO ROLE MONTE_CARLO_ROLE;

-- 5. Grant read-only access (SELECT) on the databases/schemas you want to monitor
-- GRANT USAGE ON DATABASE [YOUR_DB_NAME] TO ROLE MONTE_CARLO_ROLE;
-- GRANT USAGE ON SCHEMA [YOUR_DB_NAME].[YOUR_SCHEMA_NAME] TO ROLE MONTE_CARLO_ROLE;
-- GRANT SELECT ON ALL TABLES IN SCHEMA [YOUR_DB_NAME].[YOUR_SCHEMA_NAME] TO ROLE MONTE_CARLO_ROLE;


-- VIKINGOSGRILL_WAREHOUSE
CREATE ROLE IF NOT EXISTS MC_ROLE COMMENT = 'Role for Monte Carlo data monitoring.';
-- CREATE ROLE IF NOT EXISTS MC_ROLE;
CREATE USER IF NOT EXISTS MC_SERVICE_USER DEFAULT_ROLE = MC_ROLE DEFAULT_WAREHOUSE = VIKINGOSGRILL_WAREHOUSE;
GRANT ROLE MC_ROLE TO USER MC_SERVICE_USER;
ALTER USER MC_SERVICE_USER SET DEFAULT_ROLE = MC_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE MC_ROLE;

SHOW DATABASES;
GRANT USAGE, MONITOR ON DATABASE DGO_VIKINGOSGRILL TO ROLE MC_ROLE;

-- ALTER USER MC_SERVICE_USER SET TYPE=SERVICE DEFAULT_ROLE=MC_ROLE;


ALTER USER MC_SERVICE_USER
  SET RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtW4U2g5+0xBy8zc7OOiM
xYSiq7PF0gAZ/WiSzTfRyzZz3F4O5PF+TJh4uWYQFbbkNBaEPQwXbcWQL8YIB2e0
wq4FQYUDb126rYFlX4VhSmP4GYaqdnrjJH0zjRUR6Hfv4Rqhle0flcSgib1KLojG
CN/PWxB+ZTsKQHMK8nrp02aRHleFhS7m//xiLL210y7DlyD/Ms1EWFJdw0C/yCdL
pvfvlCzzZ07y1azn2oBdFTPNDdOxVfJv1kTDjUjL3zGzrg2hQ3gSxRI7D3kWIptR
z1tn+Q4vSoDPINhLccoXO5UuGTvKJwPv+z2zsigDpJNgQMjLWZzUDArwNQRAA7d5
TQIDAQAB';

SELECT CURRENT_ACCOUNT(), CURRENT_REGION();

-- USE ROLE MC_ROLE;
-- CNA90786.AZURE_EASTUS2
SHOW DATABASES;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE MC_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE "SNOWFLAKE" TO ROLE MC_ROLE;

GRANT USAGE, MONITOR ON DATABASE DGO_VIKINGOSGRILL TO ROLE MC_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE DGO_VIKINGOSGRILL TO ROLE MC_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE DGO_VIKINGOSGRILL TO ROLE MC_ROLE;

USE ROLE MC_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE MC_ROLE;

SHOW ROLES;
GRANT ROLE MC_ROLE TO USER JUANAQUINO;
SELECT CURRENT_USER();


USE ROLE ACCOUNTADMIN;
GRANT USAGE ON WAREHOUSE VIKINGOSGRILL_WAREHOUSE TO ROLE MC_ROLE;
GRANT OPERATE ON WAREHOUSE VIKINGOSGRILL_WAREHOUSE TO ROLE MC_ROLE;
ALTER ROLE MC_ROLE SET DEFAULT_WAREHOUSE = VIKINGOSGRILL_WAREHOUSE;



USE ROLE MC_ROLE;
SELECT CURRENT_ROLE();

GRANT ROLE MC_ROLE TO USER MC_SERVICE_USER;
ALTER USER MC_SERVICE_USER SET DEFAULT_ROLE = MC_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE MC_ROLE;

USE ROLE MC_ROLE;
SHOW SCHEMAS IN DATABASE SNOWFLAKE;
-- VIKINGOSGRILL_WAREHOUSE
ALTER USER MC_SERVICE_USER DEFAULT_WAREHOUSE = VIKINGOSGRILL_WAREHOUSE;

SELECT * FROM snowflake.account_usage.query_history where start_time >= dateadd(day, -1, CURRENT_DATE) LIMIT 1;



-----------------------------------

USE ROLE ACCOUNTADMIN; -- SECURITYADMIN / ACCOUNTADMIN

CREATE ROLE IF NOT EXISTS ANALYST_ROLE COMMENT = 'Role for data analysts.';
GRANT ROLE CLASS_ANALYST_ROLE TO ROLE SYSADMIN;





CREATE ROLE IF NOT EXISTS MONTE_CARLO_ROLE COMMENT = 'Role for Monte Carlo data monitoring.';


-- 4. Grant the role and warehouse usage
-- GRANT ROLE MONTE_CARLO_ROLE TO USER MONTE_CARLO_USER;
-- GRANT USAGE ON WAREHOUSE MONTE_CARLO_WH TO ROLE MONTE_CARLO_ROLE;

-- 5. Grant read-only access (SELECT) on the databases/schemas you want to monitor
-- GRANT USAGE ON DATABASE [YOUR_DB_NAME] TO ROLE MONTE_CARLO_ROLE;
-- GRANT USAGE ON SCHEMA [YOUR_DB_NAME].[YOUR_SCHEMA_NAME] TO ROLE MONTE_CARLO_ROLE;
-- GRANT SELECT ON ALL TABLES IN SCHEMA [YOUR_DB_NAME].[YOUR_SCHEMA_NAME] TO ROLE MONTE_CARLO_ROLE;


-- VIKINGOSGRILL_WAREHOUSE
CREATE ROLE IF NOT EXISTS MC_ROLE COMMENT = 'Role for Monte Carlo data monitoring.';
-- CREATE ROLE IF NOT EXISTS MC_ROLE;
CREATE USER IF NOT EXISTS MC_SERVICE_USER DEFAULT_ROLE = MC_ROLE DEFAULT_WAREHOUSE = VIKINGOSGRILL_WAREHOUSE;
GRANT ROLE MC_ROLE TO USER MC_SERVICE_USER;
ALTER USER MC_SERVICE_USER SET DEFAULT_ROLE = MC_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE MC_ROLE;

SHOW DATABASES;
GRANT USAGE, MONITOR ON DATABASE DGO_VIKINGOSGRILL TO ROLE MC_ROLE;

-- ALTER USER MC_SERVICE_USER SET TYPE=SERVICE DEFAULT_ROLE=MC_ROLE;


ALTER USER MC_SERVICE_USER
  SET RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtW4U2g5+0xBy8zc7OOiM
xYSiq7PF0gAZ/WiSzTfRyzZz3F4O5PF+TJh4uWYQFbbkNBaEPQwXbcWQL8YIB2e0
wq4FQYUDb126rYFlX4VhSmP4GYaqdnrjJH0zjRUR6Hfv4Rqhle0flcSgib1KLojG
CN/PWxB+ZTsKQHMK8nrp02aRHleFhS7m//xiLL210y7DlyD/Ms1EWFJdw0C/yCdL
pvfvlCzzZ07y1azn2oBdFTPNDdOxVfJv1kTDjUjL3zGzrg2hQ3gSxRI7D3kWIptR
z1tn+Q4vSoDPINhLccoXO5UuGTvKJwPv+z2zsigDpJNgQMjLWZzUDArwNQRAA7d5
TQIDAQAB';

SELECT CURRENT_ACCOUNT(), CURRENT_REGION();

-- USE ROLE MC_ROLE;
-- CNA90786.AZURE_EASTUS2
SHOW DATABASES;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE MC_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE "SNOWFLAKE" TO ROLE MC_ROLE;

GRANT USAGE, MONITOR ON DATABASE DGO_VIKINGOSGRILL TO ROLE MC_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE DGO_VIKINGOSGRILL TO ROLE MC_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE DGO_VIKINGOSGRILL TO ROLE MC_ROLE;

USE ROLE MC_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE MC_ROLE;

SHOW ROLES;
GRANT ROLE MC_ROLE TO USER JUANAQUINO;
SELECT CURRENT_USER();


USE ROLE ACCOUNTADMIN;
GRANT USAGE ON WAREHOUSE VIKINGOSGRILL_WAREHOUSE TO ROLE MC_ROLE;
GRANT OPERATE ON WAREHOUSE VIKINGOSGRILL_WAREHOUSE TO ROLE MC_ROLE;
ALTER ROLE MC_ROLE SET DEFAULT_WAREHOUSE = VIKINGOSGRILL_WAREHOUSE;



USE ROLE MC_ROLE;
SELECT CURRENT_ROLE();

GRANT ROLE MC_ROLE TO USER MC_SERVICE_USER;
ALTER USER MC_SERVICE_USER SET DEFAULT_ROLE = MC_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE MC_ROLE;

USE ROLE MC_ROLE;
SHOW SCHEMAS IN DATABASE SNOWFLAKE;
-- VIKINGOSGRILL_WAREHOUSE
ALTER USER MC_SERVICE_USER DEFAULT_WAREHOUSE = VIKINGOSGRILL_WAREHOUSE;

SELECT * FROM snowflake.account_usage.query_history where start_time >= dateadd(day, -1, CURRENT_DATE) LIMIT 1;


USE ROLE ACCOUNTADMIN;
SHOW DATABASES;

USE DATABASE DGO_VIKINGOSGRILL;
SHOW SCHEMAS;

ALTER SCHEMA BRZ_SALES_OPERATIONS RENAME TO BRONZE;
